name: Feature request
description: Suggest an enhancement
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem or opportunity
      description: What limitation are you trying to solve?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed solution
      description: Describe behavior, UX and constraints.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives considered
      description: Optional
