#pragma once

enum prefsbuttonindex {
  PREFS_BUTTON_FONT_CONFIG,
  PREFS_BUTTON_FONTSIZE,
  PREFS_BUTTON_PARASPACING,
  PREFS_BUTTON_ORIENTATION,
  PREFS_BUTTON_TIME24H,
  PREFS_BUTTON_COLORMODE,
  PREFS_BUTTON_LIBRARY_VIEW,
  PREFS_BUTTON_INDEX,
  PREFS_BUTTON_BOOKMARKS,
  PREFS_BUTTON_RESET_DEFAULTS,
  PREFS_BUTTON_CLEAR_CACHE,
  PREFS_BUTTON_COUNT
};
