#pragma once

// Text token constants — shared between format parsers and UI rendering.
// These magic numbers mark style transitions inside the text token stream.

#define TEXT_BOLD_ON 2
#define TEXT_BOLD_OFF 3
#define TEXT_ITALIC_ON 4
#define TEXT_ITALIC_OFF 5
#define TEXT_IMAGE 6
#define TEXT_IMAGE_LEADING_PARAGRAPH 7
#define TEXT_IMAGE_FIGURE_WITH_CAPTION 8
#define TEXT_IMAGE_CONTEXT_DEFAULT 14
#define TEXT_PARAGRAPH_RTL 15
#define TEXT_PARAGRAPH_LTR 16
#define TEXT_RTL_LINE_PX 17
#define TEXT_UNDERLINE_ON 18
#define TEXT_UNDERLINE_OFF 19
#define TEXT_STRIKETHROUGH_ON 20
#define TEXT_STRIKETHROUGH_OFF 21
#define TEXT_SUPERSCRIPT_ON 22
#define TEXT_SUPERSCRIPT_OFF 23
#define TEXT_SUBSCRIPT_ON 24
#define TEXT_SUBSCRIPT_OFF 25
#define TEXT_MONO_ON 26
#define TEXT_MONO_OFF 27
#define TEXT_HR 28
#define TEXT_OVERLINE_ON 29
#define TEXT_OVERLINE_OFF 30
#define TEXT_UNDERLINE_STYLE 31
#define TEXT_IMAGE_ALIGN 0x110008
#define TEXT_IMAGE_AUTHOR_WIDTH 0x11000A
#define TEXT_LINE_START_X 0x11000B
#define TEXT_FONT_SIZE 0x110007
#define TEXT_LINE_PX 35
#define TEXT_SCREEN_BREAK 0x110009
#define TEXT_LINK_START 0x110005
#define TEXT_LINK_END 0x110006
#define TEXT_PARAGRAPH_LEFT 0x110002
#define TEXT_PARAGRAPH_CENTER 0x110003
#define TEXT_PARAGRAPH_RIGHT 0x110004
#define TEXT_PRE_ON 0x110000
#define TEXT_PRE_OFF 0x110001

#define UNDERLINE_STYLE_SOLID 0
#define UNDERLINE_STYLE_DOTTED 1
#define UNDERLINE_STYLE_DASHED 2
#define UNDERLINE_STYLE_WAVY 3
#define UNDERLINE_STYLE_DOUBLE 4

#define TEXT_STYLE_REGULAR (u8)0
#define TEXT_STYLE_BOLD (u8)1
#define TEXT_STYLE_ITALIC (u8)2
#define TEXT_STYLE_BOLDITALIC (u8)3
#define TEXT_STYLE_BROWSER (u8)4
#define TEXT_STYLE_MONO (u8)5
#define TEXT_STYLE_MONO_BOLD (u8)6
#define TEXT_STYLE_MONO_ITALIC (u8)7
#define TEXT_STYLE_MONO_BOLDITALIC (u8)8
